#!/usr/bin/env bash

set -ex

echo "Installing bundler if needed..."
gem install bundler --conservative --version '>= 1.11.2'

echo "Installing gems..."
bundle check || bundle install

time bundle exec rake
